### ISSUE TITLE
Error encoding apostrophes in titles

### ISSUE THREAD

**Issue by marta-platoniq** [Platoniq/decidim-coincidim#14]
Els apòstrofs no es codifiquen bé:

![image](https://user-images.githubusercontent.com/72607737/96613406-36c87780-12ff-11eb-8480-c08144a2d9c7.png)

This happens in proposal cards (maybe others too). It seems that apostrophes are encoded with html entities.
TODO:

- [x] Check if this happens in decidim core (develop) AFFECTED
- [x] PR to decidim core
- [x] PR to `platoniq/temp/0.22-surveys`
- [x] Deploy

Also affects tag `<title>` and other metas:

![image](https://user-images.githubusercontent.com/1401520/96683461-813b0a00-137a-11eb-9fa5-e6a684ff6cbf.png)

**Comment by marta-platoniq** [comment]
It also affects the notification mail subject:

![image](https://user-images.githubusercontent.com/72607737/97346709-11ea7c00-188c-11eb-928d-9f285e08f676.png)

**Comment by microstudi** [comment]
Notes:
- the cards  errors is in meetings
